import { InvalidFilterTitleError } from "../errors/InvalidFilterTitleError";
import { FilterTitle } from "../value-objects/FilterTitle";

export type FilterCreateDetails = {
  title: string;
  color: string;
  query: string;
};

export type FilterReconstituteSource = {
  id: number;
  title: string;
  color: string;
  query: string;
};

export type FilterUpdateDetails = {
  title: string;
  color: string;
  query: string;
};

export class Filter {
  private _title: FilterTitle;
  private _color: string;
  private _query: string;

  private constructor(
    readonly id: number,
    title: FilterTitle,
    color: string,
    query: string,
  ) {
    this._title = title;
    this._color = color;
    this._query = query;
  }

  get title(): string {
    return this._title.value;
  }

  get color(): string {
    return this._color;
  }

  get query(): string {
    return this._query;
  }

  /** Factory for a filter that doesn't exist in the store yet — `id` is `0`
   * (never a real row id, since sqlite `AUTOINCREMENT` starts at 1) until
   * `IFilterStore.insert` resolves with the store-assigned one (see
   * `CreateFilterUseCase`). Validates its inputs. */
  static create(details: FilterCreateDetails): Filter {
    return new Filter(
      0,
      Filter.parseTitle(details.title),
      details.color,
      details.query,
    );
  }

  /** Rebuilds a filter from already-trusted data (a row read from the store) —
   * unlike `create`, it does not re-validate invariants, since the source was
   * already validated once, at creation time. */
  static reconstitute(source: FilterReconstituteSource): Filter {
    return new Filter(
      source.id,
      FilterTitle.of(source.title),
      source.color,
      source.query,
    );
  }

  /** Mutates this filter in place — validates the new title before any save
   * call is made. `color`/`query` carry no invariant of their own (see
   * BACKEND_CODE_STYLE_GUIDE.md — a primitive without a documented format
   * doesn't get a VO): `color` is one of the app's fixed Todoist color keys,
   * `query` is generated by the renderer's filter form, never freely typed. */
  updateDetails(details: FilterUpdateDetails): void {
    this._title = Filter.parseTitle(details.title);
    this._color = details.color;
    this._query = details.query;
  }

  private static parseTitle(rawTitle: string): FilterTitle {
    const result = FilterTitle.safeParse(rawTitle);
    if (!result.success) throw new InvalidFilterTitleError(result.error);
    return result.data;
  }
}
